language: node_js

os:
  - linux
  - osx

node_js:
  - 10
  - 9
  - 8

before_install:
  # Install npm packages and initiate build script
  - node -v
  - npm -v
  - npm install
  # - npm run build

script:
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then npm run upload-binary || exit 0; fi;