[package]
name = "rand"
version = "0.1.0"
authors = ["afdgag55 <fdh5454@outlook.com>"]
license = "ISC"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "sdfaadf"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
hfgh = "2.1.0"
vbcm = "4.6.1"
tykn = "0.5.5"
hmhg = "0.7.8"
